"""
Fix Japanese-named images for 2022-2025.

For each HTML file:
1. Read with proper encoding → get actual Japanese filenames
2. Read with errors='replace' → get garbled filenames (same as what migrate_v4 put in Markdown)
3. Map: garbled → actual backup path → new ASCII name
4. Copy actual images to public/reikai with ASCII names
5. Update Markdown file: replace garbled paths with ASCII paths
"""
import os, re, sys, shutil
from pathlib import Path
from bs4 import BeautifulSoup

sys.stdout.reconfigure(encoding='utf-8')

BACKUP = Path(r'C:\tools\ippon_backup\reikai')
OUT_CONTENT = Path(r'C:\tools\saitama-kinoko-web\src\content\reikai')
OUT_IMAGES = Path(r'C:\tools\saitama-kinoko-web\public\reikai')

TARGET_YEARS = ['2022', '2023', '2024', '2025']

PROTECTED_STEMS = {
    '2025-04-06-250406syotukinbenkyo',
    '2025-05-18-250518_soukai',
    '2025-06-29-25629_kawagoe',
    '2025-07-21-25721_ogawa',
    '2025-09-15-25915_gunmanomori',
    '2025-10-12-251012_minoyama',
    '2025-11-03-251103_akigase',
    '2025-12-07-251207_happyoukai',
    '2026-03-15-260315_saibai',
}

SKIP_NAMES = {'index', 'whatsnew'}


def detect_encoding(fp):
    with open(fp, 'rb') as f:
        raw = f.read(500)
    if b'charset=UTF-8' in raw or b'charset=utf-8' in raw:
        return 'utf-8'
    try:
        with open(fp, 'rb') as f:
            f.read().decode('utf-8')
        return 'utf-8'
    except Exception:
        return 'shift_jis'


def extract_img_srcs(html_bytes, encoding, errors='strict'):
    """Extract image src basenames from HTML bytes."""
    html = html_bytes.decode(encoding, errors=errors)
    soup = BeautifulSoup(html, 'html.parser')
    srcs = []
    for img in soup.find_all('img'):
        src = img.get('src', '')
        if src:
            srcs.append(os.path.basename(src))
    return srcs


def has_non_ascii(s):
    return any(ord(c) > 127 for c in s)


def find_md_for_html(html_stem, year):
    """Find the Markdown file for this HTML (generated by migrate_v4)."""
    clean = re.sub(r'[^\w]', '', html_stem)[:20].lower()
    candidates = list(OUT_CONTENT.glob(f'{year}-*.md'))
    # Exact suffix match
    for md in candidates:
        if md.stem.lower().endswith(clean):
            return md
    # Substring match
    for md in candidates:
        if clean in md.stem.lower():
            return md
    # Partial (first 6 chars of stem)
    short = clean[:6]
    for md in candidates:
        if short in md.stem.lower():
            return md
    return None


def process_year(year):
    year_dir = BACKUP / year
    if not year_dir.exists():
        return

    img_dest = OUT_IMAGES / year
    img_dest.mkdir(parents=True, exist_ok=True)

    # Build index of backup images: actual_unicode_name → Path
    backup_index = {}
    for f in year_dir.iterdir():
        if f.is_file() and f.suffix.lower() in ('.jpg', '.jpeg', '.png', '.gif', '.webp'):
            backup_index[f.name] = f

    html_files = sorted(
        list(year_dir.glob('*.html')) + list(year_dir.glob('*.htm')),
        key=lambda f: f.stem
    )

    total_copied = 0
    total_updated = 0

    for hf in html_files:
        if any(s in hf.stem.lower() for s in SKIP_NAMES):
            continue
        if hf.stem.lower().endswith('reikaihoukoku'):
            continue

        with open(hf, 'rb') as f:
            raw = f.read()

        enc = detect_encoding(hf)

        # Get images with proper encoding (actual Japanese names)
        actual_srcs = extract_img_srcs(raw, enc, errors='replace')
        jp_actual = [s for s in actual_srcs if has_non_ascii(s)]

        if not jp_actual:
            continue

        # Get images with errors='replace' (same garbled names as in Markdown)
        garbled_srcs = extract_img_srcs(raw, enc, errors='replace')
        jp_garbled = [s for s in garbled_srcs if has_non_ascii(s)]

        print(f'\n{hf.name}: {len(jp_actual)}件の日本語名画像')

        # Build mapping: garbled_name → (actual_name, new_ascii_name, backup_path)
        mapping = {}  # garbled → new_ascii_name
        copy_pairs = []  # (backup_path, new_ascii_name)

        prefix = re.sub(r'[^\w]', '', hf.stem)[:12]
        seen_new = set()
        counter = 1

        # Process in order of appearance (actual = garbled in this case since same decode method)
        for actual, garbled in zip(jp_actual, jp_garbled):
            garbled_norm = garbled.replace(' ', '_')
            if garbled_norm in mapping:
                continue

            # Find actual backup file
            backup_path = backup_index.get(actual)
            if not backup_path:
                # Try case-insensitive
                for k, v in backup_index.items():
                    if k.lower() == actual.lower():
                        backup_path = v
                        break

            ext = Path(actual).suffix.lower() or '.jpg'
            new_name = f'{prefix}_{counter:03d}{ext}'
            while new_name in seen_new:
                counter += 1
                new_name = f'{prefix}_{counter:03d}{ext}'
            seen_new.add(new_name)

            mapping[garbled_norm] = new_name
            # Also map without normalization
            mapping[garbled] = new_name

            if backup_path:
                copy_pairs.append((backup_path, new_name))
                print(f'  {actual[:35]} → {new_name}')
            else:
                print(f'  [MISSING] {actual[:35]} → {new_name}')

            counter += 1

        # Copy images
        for src_path, new_name in copy_pairs:
            dest = img_dest / new_name
            if not dest.exists():
                shutil.copy2(src_path, dest)
                total_copied += 1

        # Find and update Markdown
        md_file = find_md_for_html(hf.stem, year)
        if not md_file:
            print(f'  [WARN] Markdownなし: {hf.stem}')
            continue

        if md_file.stem in PROTECTED_STEMS:
            print(f'  [PROTECTED] {md_file.name}')
            continue

        content = md_file.read_text(encoding='utf-8')
        original = content

        # Replace each garbled path
        for garbled, new_name in mapping.items():
            # The garbled path may appear with spaces replaced by underscores
            garbled_in_md = garbled.replace(' ', '_')
            old_path = f'/reikai/{year}/{garbled_in_md}'
            new_path = f'/reikai/{year}/{new_name}'
            if old_path in content:
                content = content.replace(old_path, new_path)

        # Also handle any remaining non-ASCII paths via regex
        def replace_jp(m):
            path = m.group(1)
            fname = os.path.basename(path)
            if not has_non_ascii(fname):
                return path
            # Match to mapping
            fname_norm = fname.replace(' ', '_')
            for g, new in mapping.items():
                g_norm = g.replace(' ', '_')
                if fname_norm == g_norm or fname == g:
                    return f'/reikai/{year}/{new}'
            # Fallback: assign next sequential name
            return path

        content = re.sub(
            rf'(/reikai/{re.escape(year)}/[^\s\)\"\']+)',
            replace_jp,
            content
        )

        if content != original:
            md_file.write_text(content, encoding='utf-8')
            total_updated += 1
            print(f'  Markdown更新: {md_file.name}')
        else:
            print(f'  Markdownは変更なし: {md_file.name}')

    return total_copied, total_updated


def main():
    grand_copied = 0
    grand_updated = 0

    for year in TARGET_YEARS:
        print(f'\n{"="*40}')
        print(f'{year}年の処理')
        print('='*40)
        result = process_year(year)
        if result:
            c, u = result
            grand_copied += c
            grand_updated += u

    print(f'\n=== 完了 ===')
    print(f'コピー: {grand_copied}件')
    print(f'Markdown更新: {grand_updated}件')


if __name__ == '__main__':
    main()
